def agts(queue):
    queue.add('neb/neb1.py')
    queue.add('aluminium/Al_fcc.py')
    queue.add('aluminium/Al_fcc_convergence.py')
    queue.add('diffusion/initial.py')
    queue.add('diffusion/solution.py')
    queue.add('diffusion/densitydiff.py', deps=[sol])
    h2o = queue.add('vibrations/h2o.py')
    queue.add('vibrations/H2O_vib.py', deps=[h2o])
    na = queue.add('band_structure/Na_band.py')
    queue.add('band_structure/plot_band.py', deps=[na])
    si = queue.add('wannier/si.py')
    queue.add('wannier/wannier-si.py', ncpus=1, deps=[si])
    benzene = queue.add('wannier/benzene.py')
    queue.add('wannier/wannier-benzene.py', ncpus=1, deps=[benzene])
    queue.add('lrtddft/ground_state.py')
    queue.add('transport/pt_h2_tb_transport.py')
    queue.add('transport/pt_h2_transport.py')
    queue.add('wavefunctions/CO.py')
    ferro = queue.add('iron/ferro.py')
    anti = queue.add('iron/anti.py')
    non = queue.add('iron/non.py')
    queue.add('iron/PBE.py', deps=[ferro, anti, non])
