#!/usr/bin/env python

import os
import sys
import re
from optparse import OptionParser
import numpy as npy

from ase import Bohr
from ase.io.plt import write_plt
from gpaw.io.plt import read_plt

parser = OptionParser(usage='%prog dendiff [options] file1 file2',
                      version='%prog 0.1')
parser.add_option("-o", "--outfile", dest='outfile',
                  help='Name of the output file (def: script.out)')
parser.add_option("-a", "--add", action='count', default=None,
                  help='add instead of subtract')
parser.add_option("-f", "--force", action='count', default=None,
                  help='force overwriting existing files')
opt, args = parser.parse_args()
##print opt, args

def read(filename):
    cell, data, origin = read_plt(fname)
    h_c = cell.diagonal() / npy.array(data.shape) / Bohr
    dV = h_c[0] *  h_c[1] *  h_c[2]
    print '#', filename, 'norm=', npy.sum(data**2) * dV, 'sum=', npy.sum(data) * dV
    return cell, data

def write(filename, cell, data):
    h_c = cell.diagonal() / npy.array(data.shape) / Bohr
    dV = h_c[0] *  h_c[1] *  h_c[2]
    print '#', filename, 'norm=', npy.sum(data**2) * dV, 'sum=', npy.sum(data) * dV
    write_plt(filename, cell, data)

if len(args) < 2:
    print 'Missing input file names'
    sys.exit()
data = []
cell = []
for fname in args:
    cell_in, data_in = read(fname)
    data.append(data_in)
    cell.append(cell_in)
data = npy.array(data)

if data[0].shape != data[1].shape:
    raise RuntimeError('The grids do not motch')
if npy.sometrue(cell[0] != cell[1]):
    print 'Warning: cells do not match !'

if opt.outfile:
    outfname = str(opt.outfile)
else:
    outfname = 'dendiff.plt'

weight = npy.array([1., -1.])
if opt.add:
    weight[1] = 1.

res = weight[0] * data[0] + weight[1] * data[1] 
if os.path.exists(outfname) and not opt.force:
    raise RuntimeError('The file ' + outfname + ' exists. Use -f option.')
write(outfname, cell[0], res)



    



