#!/usr/bin/env python

# Emacs: treat this as -*- python -*-

import sys
from optparse import OptionParser


parser = OptionParser(usage='%prog [options] file [, file2, ...]',
                      version='%prog 0.1')
parser.add_option('-w', '--remove-wave-functions', action='store_true',
                  default=False,
                  help='Remove wave functions from restatr file.')

opt, args = parser.parse_args()

if len(args) == 0:
    print 'Missing file'
    sys.exit()

if opt.remove_wave_functions:
    for name in args:
        if name.endswith('.gpw'):
            os.system('tar -f %s --delete PseudoWaveFunctions' % name)
        else:
            import gpaw
            gpaw.Calculator.ReadAtoms(name).GetCalculator().Write(name, '')

            
