#!/usr/bin/env python

# Emacs: treat this as -*- python -*-

from optparse import OptionParser


parser = OptionParser(usage='%prog [options] [elements]',
                      version='%prog 0.1')
parser.add_option('-f', '--xcfunctional', type='string', default='LDA',
                  help='Exchange-Correlation functional (default value LDA)',
                  metavar='<XC>')
parser.add_option('-n', '--non-scalar-relativistic', action='store_true',
                  default=False,
                  help='Do *not* do a scalar-relativistic calculation.')
parser.add_option('-x', '--exact-exchange', action='store_true',
                  default=False,
                  help='Calculate exact exchange integrals.')
parser.add_option('-r', '--radius', type='string', default=None,
                  help='Cutoff radii',
                  metavar='<rcut>')
parser.add_option('-v', '--potential', type='float', default=None,
                  help='Effective potential at r=0',
                  metavar='<v0>')
parser.add_option('-l', '--logarithmic-derivatives', action='store_true',
                  help='Calculate of logarithmic derivatives.')
parser.add_option('-a', '--all-electron-only', action='store_true',
                  help='Skip generation of PAW setup.')
parser.add_option('-e', '--extra-projectors', type='string', default=None,
                  help='Extra projectors.',
                  metavar='0.0;0.0,1.0;0.0')
parser.add_option('-c', '--core', type='string', default=None,
                  help='Frozen core.  Examples: "[Ne]", "[Ar]3d".',
                  metavar='<core>')
parser.add_option('--normconserving', type='string',
                  help='Examples: s, sp')

opt, args = parser.parse_args()

from gpaw.atom.generator import Generator, parameters
from gpaw.atom.all_electron import AllElectron

if args:
    atoms = args
else:
    atoms = parameters.keys()

for symbol in atoms:
    scalarrel = not opt.non_scalar_relativistic

    if opt.all_electron_only:
        a = AllElectron(symbol, opt.xcfunctional, scalarrel)
        a.run()
        continue
    
    g = Generator(symbol, opt.xcfunctional, scalarrel)

    try:
        params = parameters[symbol]
    except KeyError:
        core = ''
        rcut = 1.0
        extra = None
        normcons = ''
    else:
        if len(params) == 2:
            core, rcut = parameters[symbol]
            extra = None
            normcons = ''
        elif len(params) == 3:
            core, rcut, extra = parameters[symbol]
            normcons = ''
        else:
            core, rcut, extra, normcons = parameters[symbol]
            
    v0 = opt.potential

    if opt.core is not None:
        core = opt.core

    if opt.radius is not None:
        rcut = [float(x) for x in opt.radius.split(',')]

    if opt.extra_projectors is not None:
        extra = {}
        if opt.extra_projectors != '':
            for l, x in enumerate(opt.extra_projectors.split(';')):
                if x != '':
                    extra[l] = [float(y) for y in x.split(',')]

    if opt.normconserving is not None:
        normcons = opt.normconserving

    g.run(core, rcut, extra,
          logderiv=opt.logarithmic_derivatives, vt0=v0,
          exx=opt.exact_exchange,
          normconserving=normcons)

