#!/usr/bin/env python

# Emacs: treat this as -*- python -*-

from optparse import OptionParser
from gridpaw.tests.dimer_report import dimer_report
from gridpaw.tests.eggboxfit import eggboxfit
from gridpaw.tests.bulk_report import bulk_report
from gridpaw.tests.hcp_report import hcp_report
import sys
import os
import pickle

parser = OptionParser(usage='%prog [options] dimer, eggbox, bulk test analyse',
                      version='%prog 0.1')

options, args = parser.parse_args()

filenames = args
ftxt = open('wiki_setups.txt', 'w')

print >> ftxt, """\
# format rst

Test results
==============
    
.. contents::

"""

for file in filenames:
    f = open(file)
    object = pickle.load(f)
    fitname = object['Test name']
    element = object['Atomic symbol']
      
    if fitname == 'dimer':
        text = dimer_report(file)
        
    elif fitname == 'eggbox':
        text = eggboxfit(file)
        
    elif fitname == 'bulk':
        text = bulk_report(file)

    elif fitname == 'hcp':
        text = hcp_report(file) 

    else:
        print 'Unknown analysis function: ', fitname

    print >> ftxt, text
