#!/usr/bin/python

# Emacs: treat this as -*- python -*-

import os
import sys
import time
import glob
import trace
import tempfile

home = os.environ['HOME']
os.environ['MATPLOTLIBDATA'] = '/home/camp/jensj/share/matplotlib/'
os.environ['DISPLAY'] = ':0.0'
sys.path.insert(0, home + '/lib/python')
import matplotlib
matplotlib.use('Agg')
import pylab

import docutils
print docutils.__version__


def send_email(subject, filename='/dev/null'):
##    assert os.system('mail -s "%s" gridpaw-developer@lists.berlios.de < %s' %
    assert os.system('mail -s "%s" jensj@fysik.dtu.dk < %s' %
                     (subject, filename)) == 0


def fail(msg, filename='/dev/null'):
    send_email(msg, filename)
    raise SystemExit


tests = ''
# For a quick test - uncomment this line:
#tests = 'PBE.py Gauss.py'

dir = tempfile.mkdtemp(prefix='gridpaw-')
os.chdir(dir)

# Checkout a fresh version and install:
if os.system('svn export ' +
             'http://svn.berlios.de/svnroot/repos/gridpaw/trunk gpaw') != 0:
    fail('Checkout of gpaw failed!')
if os.system('cvs -d :pserver:jensj@cvs.fysik.dtu.dk:/home/camp/CVSROOT ' +
             'export -r HEAD CamposASE2') != 0:
    fail('Checkout of ASE failed!')
os.chdir('gpaw')
if os.system('python setup.py install --home=%s' % dir) != 0:
    fail('Installation failed!')

os.system('mv ../CamposASE2/ASE ../lib/python')

export = ('export PYTHONPATH=%s/lib/python:%s/lib/python; ' % (dir, home) +
          'export PATH=%s/bin:$PATH; ' +
          'export GRIDPAWSETUPPATH=/usr/share/gridpaw/setups; ')

# Run test-suite:
os.chdir('test')
if os.system(export + 'python test.py -p %s >& test.out' % tests) != 0:
##if os.system(export + 'python test.py %s >& test.out' % tests) != 0:
    fail('Testsuite failed!')
lines = open('test.out').readlines()
ok = ('All tests passed!\n' in lines)

if not ok:
    # Send mail:
    subject = [line for line in lines if 'failed' in line][-1]
    send_email(subject, 'test.out')
    
out = open('/home/camp/jensj/.gridpaw/cron/test-results.txt', 'w')
print >> out, """\
.. contents::

Test results from last night
============================

::

"""
for line in lines:
    print >> out, '  ', line,
print >> out

# PyLint:
os.chdir('../../lib/python')
if os.system(export + '/home/camp/jensj/bin/pylint gridpaw; ' +
             'cp pylint_global.html /home/camp/jensj/.gridpaw/cron') != 0:
    fail('PyLint failed!')

# Generate tar-file:
os.chdir('../../gpaw')
if False:#ok:
    assert os.system('python setup.py sdist;' +
                     'cp dist/*.tar.gz /home/camp/jensj/.gridpaw/cron') == 0

# Count number of lines:
f = open('/home/camp/jensj/.gridpaw/cron/pylint_global.html')
code = 0
docstring = 0
comment = 0
while True:
    line = f.readline()
    if line == '<th>code</th>\n':
        code += int(f.readline()[4:].split('<')[0])
    elif line == '<th>docstring</th>\n':
        docstring += int(f.readline()[4:].split('<')[0])
    elif line == '<th>comment</th>\n':
        comment += int(f.readline()[4:].split('<')[0])
        break
    
c = 0
for name in (glob.glob('c/*.c') +
             glob.glob('c/*.h') +
             glob.glob('c/bmgs/*.c') +
             glob.glob('c/bmgs/*.h')):
        c += len(open(name).readlines())

# Update the stat.dat file:
f = open('/home/camp/jensj/.gridpaw/cron/stat.dat', 'a')
print >> f, pylab.epoch2num(time.time()), code, docstring, comment, c
f.close()

# Construct the stat.png file:
lines = open('/home/camp/jensj/.gridpaw/cron/stat.dat').readlines()
date, code, docstring, comment, c = zip(*[[float(x) for x in line.split()]
                                          for line in lines[1:]])
pylab.ioff()
pylab.figure(figsize=(4.0, 4.0 / (5**0.5 / 2 + 0.5)))
pylab.plot_date(date, code, 'r-', label='Python-code')
pylab.plot_date(date, docstring, 'k-', label='Python-docstring')
pylab.plot_date(date, comment, 'g-', label='Python-comment')
pylab.plot_date(date, c, 'y-', label='C-code')
pylab.plot_date(date, [0] * len(date), 'b-', label='Fortran-code')
pylab.legend()
pylab.title('Number of lines')
pylab.savefig('/home/camp/jensj/.gridpaw/cron/stat.png')

f = open('/home/camp/jensj/.gridpaw/cron/stat.txt', 'w')
print >> f, """\

.. image:: stat.png


"""

# Coverage test:
os.chdir('test')
day = time.localtime()[6]
if ok and day == 6:  # only Sunday
    if os.system(export +
                 'rm /home/camp/jensj/.gridpaw/cron/*.cover; ' +
                 'python %s/trace.py' % os.path.dirname(trace.__file__) +
                 ' --count --coverdir coverage --missing' +
                 ' --ignore-dir /usr:%s test.py %s' % (home, tests)) != 0:
        fail('Coverage failed!')
    
    filenames = glob.glob('coverage/gridpaw.*.cover')
else:
    filenames = glob.glob('/home/camp/jensj/.gridpaw/cron/*.cover')
    
names = []
for filename in filenames:
    missing = 0
    for line in open(filename):
        if line.startswith('>>>>>>'):
            missing += 1
    if missing > 0:
        if filename.startswith('coverage/gridpaw.'):
            name = filename[17:-6]
            if os.system('cp %s /home/camp/jensj/.gridpaw/cron/%s.cover' %
                         (filename, name)) != 0:
                fail('????')
        else:
            name = filename[31:-6]
        names.append((-missing, name))

print >> out, """\

Coverage
========

"""
if len(names) > 0:
    m = 1 + max([len(name) for n, name in names])
    sep = ' ' + m * '=' + '  ====='
    print >> out, 'Test-suite does not cover all of the code!'
    print >> out, 'Number of missing lines:'
    print >> out
    print >> out, sep
    print >> out, ' %-*s  Lines' % (m, 'Module')
    print >> out, sep
    names.sort()
    for n, name in names:
        print >> out, ' %-*s  %d' % (m, name + '_', -n)
    print >> out, sep
    print >> out
    url = 'http://wiki.fysik.dtu.dk/stuff'
    for n, name in names:
        print >> out, '.. _%s: %s/%s.cover' % (name, url, name)
else:
    print >> out, 'Congratulations - the tests covers all of the code!'
print >> out
print >> out, '(coverage-test is performed Sunday nights only)'

os.system(export + 'cd ..; epydoc --docformat restructuredtext ' +
          '--name gridpaw --url http://wiki.fysik.dtu.dk/gridcode gridpaw ' +
          '>& warnings; ' +
          'rm -rf /home/camp/jensj/.gridpaw/cron/html; ' +
          'cp -rp html /home/camp/jensj/.gridpaw/cron')

if 'Warning:' in open('../warnings').read():
    pass#send_email('Warning(s) from epydoc!', '../warnings')

#os.system('cd; rm -r ' + dir)

