/* Generated by Cython 0.11.2 on Tue Jun 15 02:58:39 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef Py_PYTHON_H
    #error Python headers needed to compile C extensions, please install development version of Python.
#endif
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
  #define PyDict_CheckExact(op) (Py_TYPE(op) == &PyDict_Type)
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PY_FORMAT_SIZE_T ""
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyString_CheckExact          PyBytes_CheckExact
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
  #ifndef __fastcall
    #define __fastcall
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),((char *)(n)))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),((char *)(n)),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),((char *)(n)))
#else
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),(n))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),(n),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),(n))
#endif
#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_NAMESTR(n) ((char *)(n))
  #define __Pyx_DOCSTR(n)  ((char *)(n))
#else
  #define __Pyx_NAMESTR(n) (n)
  #define __Pyx_DOCSTR(n)  (n)
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__h5py__h5z
#include "stdlib.h"
#include "string.h"
#include "time.h"
#include "unistd.h"
#include "stdint.h"
#include "compat.h"
#include "lzf_filter.h"
#include "hdf5.h"
#define __PYX_USE_C99_COMPLEX defined(_Complex_I)


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString          PyString_FromString
#define __Pyx_PyBytes_FromStringAndSize   PyString_FromStringAndSize
#define __Pyx_PyBytes_AsString            PyString_AsString
#else
#define __Pyx_PyBytes_FromString          PyBytes_FromString
#define __Pyx_PyBytes_FromStringAndSize   PyBytes_FromStringAndSize
#define __Pyx_PyBytes_AsString            PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject*);
static INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x);

#if !defined(T_PYSSIZET)
#if PY_VERSION_HEX < 0x02050000
#define T_PYSSIZET T_INT
#elif !defined(T_LONGLONG)
#define T_PYSSIZET \
        ((sizeof(Py_ssize_t) == sizeof(int))  ? T_INT  : \
        ((sizeof(Py_ssize_t) == sizeof(long)) ? T_LONG : -1))
#else
#define T_PYSSIZET \
        ((sizeof(Py_ssize_t) == sizeof(int))          ? T_INT      : \
        ((sizeof(Py_ssize_t) == sizeof(long))         ? T_LONG     : \
        ((sizeof(Py_ssize_t) == sizeof(PY_LONG_LONG)) ? T_LONGLONG : -1)))
#endif
#endif

#if !defined(T_SIZET)
#if !defined(T_ULONGLONG)
#define T_SIZET \
        ((sizeof(size_t) == sizeof(unsigned int))  ? T_UINT  : \
        ((sizeof(size_t) == sizeof(unsigned long)) ? T_ULONG : -1))
#else
#define T_SIZET \
        ((sizeof(size_t) == sizeof(unsigned int))          ? T_UINT      : \
        ((sizeof(size_t) == sizeof(unsigned long))         ? T_ULONG     : \
        ((sizeof(size_t) == sizeof(unsigned PY_LONG_LONG)) ? T_ULONGLONG : -1)))
#endif
#endif

static INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject*);
static INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t);
static INLINE size_t __Pyx_PyInt_AsSize_t(PyObject*);

#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))


#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static char __pyx_mdoc[] = "\n    Filter API and constants.\n";


#ifdef CYTHON_REFNANNY
typedef struct {
  void (*INCREF)(void*, PyObject*, int);
  void (*DECREF)(void*, PyObject*, int);
  void (*GOTREF)(void*, PyObject*, int);
  void (*GIVEREF)(void*, PyObject*, int);
  void* (*NewContext)(const char*, int, const char*);
  void (*FinishContext)(void**);
} __Pyx_RefnannyAPIStruct;
static __Pyx_RefnannyAPIStruct *__Pyx_Refnanny = NULL;
#define __Pyx_ImportRefcountAPI(name)   (__Pyx_RefnannyAPIStruct *) PyCObject_Import((char *)name, (char *)"RefnannyAPI")
#define __Pyx_INCREF(r) __Pyx_Refnanny->INCREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_DECREF(r) __Pyx_Refnanny->DECREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_GOTREF(r) __Pyx_Refnanny->GOTREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_GIVEREF(r) __Pyx_Refnanny->GIVEREF(__pyx_refchk, (PyObject *)(r), __LINE__)
#define __Pyx_XDECREF(r) if((r) == NULL) ; else __Pyx_DECREF(r)
#define __Pyx_SetupRefcountContext(name)   void* __pyx_refchk = __Pyx_Refnanny->NewContext((name), __LINE__, __FILE__)
#define __Pyx_FinishRefcountContext()   __Pyx_Refnanny->FinishContext(&__pyx_refchk)
#else
#define __Pyx_INCREF(r) Py_INCREF(r)
#define __Pyx_DECREF(r) Py_DECREF(r)
#define __Pyx_GOTREF(r)
#define __Pyx_GIVEREF(r)
#define __Pyx_XDECREF(r) Py_XDECREF(r)
#define __Pyx_SetupRefcountContext(name)
#define __Pyx_FinishRefcountContext()
#endif /* CYTHON_REFNANNY */
#define __Pyx_XGIVEREF(r) if((r) == NULL) ; else __Pyx_GIVEREF(r)
#define __Pyx_XGOTREF(r) if((r) == NULL) ; else __Pyx_GOTREF(r)

static INLINE int __Pyx_StrEq(const char *, const char *); /*proto*/

static INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject *);

static INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject *);

static INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject *);

static INLINE char __Pyx_PyInt_AsChar(PyObject *);

static INLINE short __Pyx_PyInt_AsShort(PyObject *);

static INLINE int __Pyx_PyInt_AsInt(PyObject *);

static INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject *);

static INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject *);

static INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject *);

static INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject *);

static INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject *);

static INLINE long __Pyx_PyInt_AsLong(PyObject *);

static INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject *);

static INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject *);

static INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject *);

static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(const char *name); /*proto*/

static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */

/* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5.pxd":15
 * include "defs.pxd"
 * 
 * cdef class H5PYConfig:             # <<<<<<<<<<<<<<
 * 
 *     cdef object _r_name
 */

struct __pyx_obj_4h5py_2h5_H5PYConfig {
  PyObject_HEAD
  PyObject *_r_name;
  PyObject *_i_name;
  PyObject *_f_name;
  PyObject *_t_name;
  PyObject *API_16;
  PyObject *API_18;
  PyObject *DEBUG;
  PyObject *THREADS;
};

/* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5.pxd":28
 * cpdef H5PYConfig get_config()
 * 
 * cdef class ObjectID:             # <<<<<<<<<<<<<<
 * 
 *     cdef object __weakref__
 */

struct __pyx_obj_4h5py_2h5_ObjectID {
  PyObject_HEAD
  PyObject *__weakref__;
  hid_t id;
  int _locked;
  PyObject *_hash;
};

/* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5.pxd":35
 *     cdef object _hash
 * 
 * cdef class SmartStruct:             # <<<<<<<<<<<<<<
 *     cdef object __weakref__
 *     cdef object _title
 */

struct __pyx_obj_4h5py_2h5_SmartStruct {
  PyObject_HEAD
  PyObject *__weakref__;
  PyObject *_title;
};
/* Module declarations from h5py.h5 */

static PyTypeObject *__pyx_ptype_4h5py_2h5_H5PYConfig = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_ObjectID = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_SmartStruct = 0;
__PYX_EXTERN_C int hdf5_inited;
static struct __pyx_obj_4h5py_2h5_H5PYConfig *(*__pyx_f_4h5py_2h5_get_config)(int __pyx_skip_dispatch); /*proto*/
static int (*__pyx_f_4h5py_2h5_init_hdf5)(void); /*proto*/
/* Module declarations from h5py.h5z */

#define __Pyx_MODULE_NAME "h5z"
int __pyx_module_is_main_h5py__h5z = 0;

/* Implementation of h5py.h5z */
static char __pyx_k___main__[] = "__main__";
static PyObject *__pyx_kp___main__;
static char __pyx_k_filter_code[] = "filter_code";
static PyObject *__pyx_kp_filter_code;
static char __pyx_k_FILTER_LZF[] = "FILTER_LZF";
static PyObject *__pyx_kp_FILTER_LZF;
static char __pyx_k_FILTER_ERROR[] = "FILTER_ERROR";
static PyObject *__pyx_kp_FILTER_ERROR;
static char __pyx_k_FILTER_NONE[] = "FILTER_NONE";
static PyObject *__pyx_kp_FILTER_NONE;
static char __pyx_k_FILTER_ALL[] = "FILTER_ALL";
static PyObject *__pyx_kp_FILTER_ALL;
static char __pyx_k_FILTER_DEFLATE[] = "FILTER_DEFLATE";
static PyObject *__pyx_kp_FILTER_DEFLATE;
static char __pyx_k_FILTER_SHUFFLE[] = "FILTER_SHUFFLE";
static PyObject *__pyx_kp_FILTER_SHUFFLE;
static char __pyx_k_1[] = "FILTER_FLETCHER32";
static PyObject *__pyx_kp_1;
static char __pyx_k_FILTER_SZIP[] = "FILTER_SZIP";
static PyObject *__pyx_kp_FILTER_SZIP;
static char __pyx_k_FILTER_RESERVED[] = "FILTER_RESERVED";
static PyObject *__pyx_kp_FILTER_RESERVED;
static char __pyx_k_FILTER_MAX[] = "FILTER_MAX";
static PyObject *__pyx_kp_FILTER_MAX;
static char __pyx_k_FLAG_DEFMASK[] = "FLAG_DEFMASK";
static PyObject *__pyx_kp_FLAG_DEFMASK;
static char __pyx_k_FLAG_MANDATORY[] = "FLAG_MANDATORY";
static PyObject *__pyx_kp_FLAG_MANDATORY;
static char __pyx_k_FLAG_OPTIONAL[] = "FLAG_OPTIONAL";
static PyObject *__pyx_kp_FLAG_OPTIONAL;
static char __pyx_k_FLAG_INVMASK[] = "FLAG_INVMASK";
static PyObject *__pyx_kp_FLAG_INVMASK;
static char __pyx_k_FLAG_REVERSE[] = "FLAG_REVERSE";
static PyObject *__pyx_kp_FLAG_REVERSE;
static char __pyx_k_FLAG_SKIP_EDC[] = "FLAG_SKIP_EDC";
static PyObject *__pyx_kp_FLAG_SKIP_EDC;
static char __pyx_k_2[] = "SZIP_ALLOW_K13_OPTION_MASK";
static PyObject *__pyx_kp_2;
static char __pyx_k_3[] = "SZIP_CHIP_OPTION_MASK";
static PyObject *__pyx_kp_3;
static char __pyx_k_SZIP_EC_OPTION_MASK[] = "SZIP_EC_OPTION_MASK";
static PyObject *__pyx_kp_SZIP_EC_OPTION_MASK;
static char __pyx_k_SZIP_NN_OPTION_MASK[] = "SZIP_NN_OPTION_MASK";
static PyObject *__pyx_kp_SZIP_NN_OPTION_MASK;
static char __pyx_k_4[] = "SZIP_MAX_PIXELS_PER_BLOCK";
static PyObject *__pyx_kp_4;
static char __pyx_k_5[] = "FILTER_CONFIG_ENCODE_ENABLED";
static PyObject *__pyx_kp_5;
static char __pyx_k_6[] = "FILTER_CONFIG_DECODE_ENABLED";
static PyObject *__pyx_kp_6;
static char __pyx_k_ERROR_EDC[] = "ERROR_EDC";
static PyObject *__pyx_kp_ERROR_EDC;
static char __pyx_k_DISABLE_EDC[] = "DISABLE_EDC";
static PyObject *__pyx_kp_DISABLE_EDC;
static char __pyx_k_ENABLE_EDC[] = "ENABLE_EDC";
static PyObject *__pyx_kp_ENABLE_EDC;
static char __pyx_k_NO_EDC[] = "NO_EDC";
static PyObject *__pyx_kp_NO_EDC;

/* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":64
 * 
 * 
 * def filter_avail(int filter_code):             # <<<<<<<<<<<<<<
 *     """(INT filter_code) => BOOL
 * 
 */

static PyObject *__pyx_pf_4h5py_3h5z_filter_avail(PyObject *__pyx_self, PyObject *__pyx_arg_filter_code); /*proto*/
static char __pyx_doc_4h5py_3h5z_filter_avail[] = "(INT filter_code) => BOOL\n\n    Determine if the given filter is available to the library. The\n    filter code should be one of:\n\n    - FILTER_DEFLATE\n    - FILTER_SHUFFLE\n    - FILTER_FLETCHER32\n    - FILTER_SZIP\n    ";
static PyObject *__pyx_pf_4h5py_3h5z_filter_avail(PyObject *__pyx_self, PyObject *__pyx_arg_filter_code) {
  int __pyx_v_filter_code;
  PyObject *__pyx_r = NULL;
  htri_t __pyx_t_1;
  PyObject *__pyx_t_2 = NULL;
  __Pyx_SetupRefcountContext("filter_avail");
  __pyx_self = __pyx_self;
  assert(__pyx_arg_filter_code); {
    __pyx_v_filter_code = __Pyx_PyInt_AsInt(__pyx_arg_filter_code); if (unlikely((__pyx_v_filter_code == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L3_error:;
  __Pyx_AddTraceback("h5z.filter_avail");
  return NULL;
  __pyx_L4_argument_unpacking_done:;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":75
 *     - FILTER_SZIP
 *     """
 *     return <bint>H5Zfilter_avail(<H5Z_filter_t>filter_code)             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __Pyx_XDECREF(__pyx_r);
  __pyx_t_1 = H5Zfilter_avail(((H5Z_filter_t)__pyx_v_filter_code)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_t_2 = __Pyx_PyBool_FromLong(((int)__pyx_t_1)); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  __pyx_r = __pyx_t_2;
  __pyx_t_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_AddTraceback("h5z.filter_avail");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_FinishRefcountContext();
  return __pyx_r;
}

/* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":78
 * 
 * 
 * def get_filter_info(int filter_code):             # <<<<<<<<<<<<<<
 *     """(INT filter_code) => INT filter_flags
 * 
 */

static PyObject *__pyx_pf_4h5py_3h5z_get_filter_info(PyObject *__pyx_self, PyObject *__pyx_arg_filter_code); /*proto*/
static char __pyx_doc_4h5py_3h5z_get_filter_info[] = "(INT filter_code) => INT filter_flags\n\n    Retrieve a bitfield with information about the given filter. The\n    filter code should be one of:\n\n    - FILTER_DEFLATE\n    - FILTER_SHUFFLE\n    - FILTER_FLETCHER32\n    - FILTER_SZIP\n\n    Valid bitmasks for use with the returned bitfield are:\n\n    - FILTER_CONFIG_ENCODE_ENABLED\n    - FILTER_CONFIG_DECODE_ENABLED\n    ";
static PyObject *__pyx_pf_4h5py_3h5z_get_filter_info(PyObject *__pyx_self, PyObject *__pyx_arg_filter_code) {
  int __pyx_v_filter_code;
  unsigned int __pyx_v_flags;
  PyObject *__pyx_r = NULL;
  herr_t __pyx_t_1;
  PyObject *__pyx_t_2 = NULL;
  __Pyx_SetupRefcountContext("get_filter_info");
  __pyx_self = __pyx_self;
  assert(__pyx_arg_filter_code); {
    __pyx_v_filter_code = __Pyx_PyInt_AsInt(__pyx_arg_filter_code); if (unlikely((__pyx_v_filter_code == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L3_error:;
  __Pyx_AddTraceback("h5z.get_filter_info");
  return NULL;
  __pyx_L4_argument_unpacking_done:;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":95
 *     """
 *     cdef unsigned int flags
 *     H5Zget_filter_info(<H5Z_filter_t>filter_code, &flags)             # <<<<<<<<<<<<<<
 *     return flags
 * 
 */
  __pyx_t_1 = H5Zget_filter_info(((H5Z_filter_t)__pyx_v_filter_code), (&__pyx_v_flags)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":96
 *     cdef unsigned int flags
 *     H5Zget_filter_info(<H5Z_filter_t>filter_code, &flags)
 *     return flags             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __Pyx_XDECREF(__pyx_r);
  __pyx_t_2 = PyLong_FromUnsignedLong(__pyx_v_flags); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  __pyx_r = __pyx_t_2;
  __pyx_t_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_AddTraceback("h5z.get_filter_info");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_FinishRefcountContext();
  return __pyx_r;
}

/* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5.pxd":31
 * 
 *     cdef object __weakref__
 *     cdef readonly hid_t id             # <<<<<<<<<<<<<<
 *     cdef readonly int _locked
 *     cdef object _hash
 */

static PyObject *__pyx_pf_4h5py_2h5_8ObjectID_2id___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_pf_4h5py_2h5_8ObjectID_2id___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r = NULL;
  PyObject *__pyx_t_1 = NULL;
  __Pyx_SetupRefcountContext("__get__");
  __Pyx_XDECREF(__pyx_r);
  __pyx_t_1 = PyInt_FromLong(((struct __pyx_obj_4h5py_2h5_ObjectID *)__pyx_v_self)->id); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_r = __pyx_t_1;
  __pyx_t_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_1);
  __Pyx_AddTraceback("h5.ObjectID.id.__get__");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_FinishRefcountContext();
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {__Pyx_NAMESTR("filter_avail"), (PyCFunction)__pyx_pf_4h5py_3h5z_filter_avail, METH_O, __Pyx_DOCSTR(__pyx_doc_4h5py_3h5z_filter_avail)},
  {__Pyx_NAMESTR("get_filter_info"), (PyCFunction)__pyx_pf_4h5py_3h5z_get_filter_info, METH_O, __Pyx_DOCSTR(__pyx_doc_4h5py_3h5z_get_filter_info)},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    __Pyx_NAMESTR("h5z"),
    __Pyx_DOCSTR(__pyx_mdoc), /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp___main__, __pyx_k___main__, sizeof(__pyx_k___main__), 1, 1, 1},
  {&__pyx_kp_filter_code, __pyx_k_filter_code, sizeof(__pyx_k_filter_code), 1, 1, 1},
  {&__pyx_kp_FILTER_LZF, __pyx_k_FILTER_LZF, sizeof(__pyx_k_FILTER_LZF), 1, 1, 1},
  {&__pyx_kp_FILTER_ERROR, __pyx_k_FILTER_ERROR, sizeof(__pyx_k_FILTER_ERROR), 1, 1, 1},
  {&__pyx_kp_FILTER_NONE, __pyx_k_FILTER_NONE, sizeof(__pyx_k_FILTER_NONE), 1, 1, 1},
  {&__pyx_kp_FILTER_ALL, __pyx_k_FILTER_ALL, sizeof(__pyx_k_FILTER_ALL), 1, 1, 1},
  {&__pyx_kp_FILTER_DEFLATE, __pyx_k_FILTER_DEFLATE, sizeof(__pyx_k_FILTER_DEFLATE), 1, 1, 1},
  {&__pyx_kp_FILTER_SHUFFLE, __pyx_k_FILTER_SHUFFLE, sizeof(__pyx_k_FILTER_SHUFFLE), 1, 1, 1},
  {&__pyx_kp_1, __pyx_k_1, sizeof(__pyx_k_1), 1, 1, 1},
  {&__pyx_kp_FILTER_SZIP, __pyx_k_FILTER_SZIP, sizeof(__pyx_k_FILTER_SZIP), 1, 1, 1},
  {&__pyx_kp_FILTER_RESERVED, __pyx_k_FILTER_RESERVED, sizeof(__pyx_k_FILTER_RESERVED), 1, 1, 1},
  {&__pyx_kp_FILTER_MAX, __pyx_k_FILTER_MAX, sizeof(__pyx_k_FILTER_MAX), 1, 1, 1},
  {&__pyx_kp_FLAG_DEFMASK, __pyx_k_FLAG_DEFMASK, sizeof(__pyx_k_FLAG_DEFMASK), 1, 1, 1},
  {&__pyx_kp_FLAG_MANDATORY, __pyx_k_FLAG_MANDATORY, sizeof(__pyx_k_FLAG_MANDATORY), 1, 1, 1},
  {&__pyx_kp_FLAG_OPTIONAL, __pyx_k_FLAG_OPTIONAL, sizeof(__pyx_k_FLAG_OPTIONAL), 1, 1, 1},
  {&__pyx_kp_FLAG_INVMASK, __pyx_k_FLAG_INVMASK, sizeof(__pyx_k_FLAG_INVMASK), 1, 1, 1},
  {&__pyx_kp_FLAG_REVERSE, __pyx_k_FLAG_REVERSE, sizeof(__pyx_k_FLAG_REVERSE), 1, 1, 1},
  {&__pyx_kp_FLAG_SKIP_EDC, __pyx_k_FLAG_SKIP_EDC, sizeof(__pyx_k_FLAG_SKIP_EDC), 1, 1, 1},
  {&__pyx_kp_2, __pyx_k_2, sizeof(__pyx_k_2), 1, 1, 1},
  {&__pyx_kp_3, __pyx_k_3, sizeof(__pyx_k_3), 1, 1, 1},
  {&__pyx_kp_SZIP_EC_OPTION_MASK, __pyx_k_SZIP_EC_OPTION_MASK, sizeof(__pyx_k_SZIP_EC_OPTION_MASK), 1, 1, 1},
  {&__pyx_kp_SZIP_NN_OPTION_MASK, __pyx_k_SZIP_NN_OPTION_MASK, sizeof(__pyx_k_SZIP_NN_OPTION_MASK), 1, 1, 1},
  {&__pyx_kp_4, __pyx_k_4, sizeof(__pyx_k_4), 1, 1, 1},
  {&__pyx_kp_5, __pyx_k_5, sizeof(__pyx_k_5), 1, 1, 1},
  {&__pyx_kp_6, __pyx_k_6, sizeof(__pyx_k_6), 1, 1, 1},
  {&__pyx_kp_ERROR_EDC, __pyx_k_ERROR_EDC, sizeof(__pyx_k_ERROR_EDC), 1, 1, 1},
  {&__pyx_kp_DISABLE_EDC, __pyx_k_DISABLE_EDC, sizeof(__pyx_k_DISABLE_EDC), 1, 1, 1},
  {&__pyx_kp_ENABLE_EDC, __pyx_k_ENABLE_EDC, sizeof(__pyx_k_ENABLE_EDC), 1, 1, 1},
  {&__pyx_kp_NO_EDC, __pyx_k_NO_EDC, sizeof(__pyx_k_NO_EDC), 1, 1, 1},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  return 0;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inith5z(void); /*proto*/
PyMODINIT_FUNC inith5z(void)
#else
PyMODINIT_FUNC PyInit_h5z(void); /*proto*/
PyMODINIT_FUNC PyInit_h5z(void)
#endif
{
  PyObject *__pyx_1 = 0;
  int __pyx_t_1;
  PyObject *__pyx_t_2 = NULL;
  #ifdef CYTHON_REFNANNY
  void* __pyx_refchk = NULL;
  __Pyx_Refnanny = __Pyx_ImportRefcountAPI("refnanny");
  if (!__Pyx_Refnanny) {
      PyErr_Clear();
      __Pyx_Refnanny = __Pyx_ImportRefcountAPI("Cython.Runtime.refnanny");
      if (!__Pyx_Refnanny)
          Py_FatalError("failed to import refnanny module");
  }
  __pyx_refchk = __Pyx_Refnanny->NewContext("PyMODINIT_FUNC PyInit_h5z(void)", __LINE__, __FILE__);
  #endif
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Library function declarations ---*/
  __pyx_init_filenames();
  /*--- Threads initialization code ---*/
  #if defined(__PYX_FORCE_INIT_THREADS) && __PYX_FORCE_INIT_THREADS
  #ifdef WITH_THREAD /* Python build with threading support? */
  PyEval_InitThreads();
  #endif
  #endif
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4(__Pyx_NAMESTR("h5z"), __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_NAMESTR(__Pyx_BUILTIN_MODULE_NAME));
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__pyx_module_is_main_h5py__h5z) {
    if (__Pyx_SetAttrString(__pyx_m, "__name__", __pyx_kp___main__) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  }
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  __pyx_ptype_4h5py_2h5_H5PYConfig = __Pyx_ImportType("h5", "H5PYConfig", sizeof(struct __pyx_obj_4h5py_2h5_H5PYConfig)); if (unlikely(!__pyx_ptype_4h5py_2h5_H5PYConfig)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_ObjectID = __Pyx_ImportType("h5", "ObjectID", sizeof(struct __pyx_obj_4h5py_2h5_ObjectID)); if (unlikely(!__pyx_ptype_4h5py_2h5_ObjectID)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_SmartStruct = __Pyx_ImportType("h5", "SmartStruct", sizeof(struct __pyx_obj_4h5py_2h5_SmartStruct)); if (unlikely(!__pyx_ptype_4h5py_2h5_SmartStruct)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Function import code ---*/
  __pyx_1 = __Pyx_ImportModule("h5"); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_1, "get_config", (void (**)(void))&__pyx_f_4h5py_2h5_get_config, "struct __pyx_obj_4h5py_2h5_H5PYConfig *(int __pyx_skip_dispatch)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_1, "init_hdf5", (void (**)(void))&__pyx_f_4h5py_2h5_init_hdf5, "int (void)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  /*--- Execution code ---*/

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":23
 * 
 * # Initialization
 * init_hdf5()             # <<<<<<<<<<<<<<
 * 
 * # === Public constants and data structures ====================================
 */
  __pyx_t_1 = __pyx_f_4h5py_2h5_init_hdf5(); if (unlikely(__pyx_t_1 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":27
 * # === Public constants and data structures ====================================
 * 
 * FILTER_LZF = H5PY_FILTER_LZF             # <<<<<<<<<<<<<<
 * 
 * FILTER_ERROR    = H5Z_FILTER_ERROR
 */
  __pyx_t_2 = PyInt_FromLong(H5PY_FILTER_LZF); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_LZF, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":29
 * FILTER_LZF = H5PY_FILTER_LZF
 * 
 * FILTER_ERROR    = H5Z_FILTER_ERROR             # <<<<<<<<<<<<<<
 * FILTER_NONE     = H5Z_FILTER_NONE
 * FILTER_ALL      = H5Z_FILTER_ALL
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_ERROR); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_ERROR, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":30
 * 
 * FILTER_ERROR    = H5Z_FILTER_ERROR
 * FILTER_NONE     = H5Z_FILTER_NONE             # <<<<<<<<<<<<<<
 * FILTER_ALL      = H5Z_FILTER_ALL
 * FILTER_DEFLATE  = H5Z_FILTER_DEFLATE
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_NONE); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_NONE, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":31
 * FILTER_ERROR    = H5Z_FILTER_ERROR
 * FILTER_NONE     = H5Z_FILTER_NONE
 * FILTER_ALL      = H5Z_FILTER_ALL             # <<<<<<<<<<<<<<
 * FILTER_DEFLATE  = H5Z_FILTER_DEFLATE
 * FILTER_SHUFFLE  = H5Z_FILTER_SHUFFLE
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_ALL); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_ALL, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":32
 * FILTER_NONE     = H5Z_FILTER_NONE
 * FILTER_ALL      = H5Z_FILTER_ALL
 * FILTER_DEFLATE  = H5Z_FILTER_DEFLATE             # <<<<<<<<<<<<<<
 * FILTER_SHUFFLE  = H5Z_FILTER_SHUFFLE
 * FILTER_FLETCHER32 = H5Z_FILTER_FLETCHER32
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_DEFLATE); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_DEFLATE, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":33
 * FILTER_ALL      = H5Z_FILTER_ALL
 * FILTER_DEFLATE  = H5Z_FILTER_DEFLATE
 * FILTER_SHUFFLE  = H5Z_FILTER_SHUFFLE             # <<<<<<<<<<<<<<
 * FILTER_FLETCHER32 = H5Z_FILTER_FLETCHER32
 * FILTER_SZIP     = H5Z_FILTER_SZIP
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_SHUFFLE); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_SHUFFLE, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":34
 * FILTER_DEFLATE  = H5Z_FILTER_DEFLATE
 * FILTER_SHUFFLE  = H5Z_FILTER_SHUFFLE
 * FILTER_FLETCHER32 = H5Z_FILTER_FLETCHER32             # <<<<<<<<<<<<<<
 * FILTER_SZIP     = H5Z_FILTER_SZIP
 * FILTER_RESERVED = H5Z_FILTER_RESERVED
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_FLETCHER32); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_1, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":35
 * FILTER_SHUFFLE  = H5Z_FILTER_SHUFFLE
 * FILTER_FLETCHER32 = H5Z_FILTER_FLETCHER32
 * FILTER_SZIP     = H5Z_FILTER_SZIP             # <<<<<<<<<<<<<<
 * FILTER_RESERVED = H5Z_FILTER_RESERVED
 * FILTER_MAX      = H5Z_FILTER_MAX
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_SZIP); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_SZIP, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":36
 * FILTER_FLETCHER32 = H5Z_FILTER_FLETCHER32
 * FILTER_SZIP     = H5Z_FILTER_SZIP
 * FILTER_RESERVED = H5Z_FILTER_RESERVED             # <<<<<<<<<<<<<<
 * FILTER_MAX      = H5Z_FILTER_MAX
 * 
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_RESERVED); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_RESERVED, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":37
 * FILTER_SZIP     = H5Z_FILTER_SZIP
 * FILTER_RESERVED = H5Z_FILTER_RESERVED
 * FILTER_MAX      = H5Z_FILTER_MAX             # <<<<<<<<<<<<<<
 * 
 * FLAG_DEFMASK    = H5Z_FLAG_DEFMASK
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_MAX); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_MAX, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":39
 * FILTER_MAX      = H5Z_FILTER_MAX
 * 
 * FLAG_DEFMASK    = H5Z_FLAG_DEFMASK             # <<<<<<<<<<<<<<
 * FLAG_MANDATORY  = H5Z_FLAG_MANDATORY
 * FLAG_OPTIONAL   = H5Z_FLAG_OPTIONAL
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FLAG_DEFMASK); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_DEFMASK, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":40
 * 
 * FLAG_DEFMASK    = H5Z_FLAG_DEFMASK
 * FLAG_MANDATORY  = H5Z_FLAG_MANDATORY             # <<<<<<<<<<<<<<
 * FLAG_OPTIONAL   = H5Z_FLAG_OPTIONAL
 * FLAG_INVMASK    = H5Z_FLAG_INVMASK
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FLAG_MANDATORY); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_MANDATORY, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":41
 * FLAG_DEFMASK    = H5Z_FLAG_DEFMASK
 * FLAG_MANDATORY  = H5Z_FLAG_MANDATORY
 * FLAG_OPTIONAL   = H5Z_FLAG_OPTIONAL             # <<<<<<<<<<<<<<
 * FLAG_INVMASK    = H5Z_FLAG_INVMASK
 * FLAG_REVERSE    = H5Z_FLAG_REVERSE
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FLAG_OPTIONAL); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_OPTIONAL, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":42
 * FLAG_MANDATORY  = H5Z_FLAG_MANDATORY
 * FLAG_OPTIONAL   = H5Z_FLAG_OPTIONAL
 * FLAG_INVMASK    = H5Z_FLAG_INVMASK             # <<<<<<<<<<<<<<
 * FLAG_REVERSE    = H5Z_FLAG_REVERSE
 * FLAG_SKIP_EDC   = H5Z_FLAG_SKIP_EDC
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FLAG_INVMASK); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_INVMASK, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":43
 * FLAG_OPTIONAL   = H5Z_FLAG_OPTIONAL
 * FLAG_INVMASK    = H5Z_FLAG_INVMASK
 * FLAG_REVERSE    = H5Z_FLAG_REVERSE             # <<<<<<<<<<<<<<
 * FLAG_SKIP_EDC   = H5Z_FLAG_SKIP_EDC
 * 
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FLAG_REVERSE); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_REVERSE, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":44
 * FLAG_INVMASK    = H5Z_FLAG_INVMASK
 * FLAG_REVERSE    = H5Z_FLAG_REVERSE
 * FLAG_SKIP_EDC   = H5Z_FLAG_SKIP_EDC             # <<<<<<<<<<<<<<
 * 
 * SZIP_ALLOW_K13_OPTION_MASK  = H5_SZIP_ALLOW_K13_OPTION_MASK   #1
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FLAG_SKIP_EDC); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_SKIP_EDC, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":46
 * FLAG_SKIP_EDC   = H5Z_FLAG_SKIP_EDC
 * 
 * SZIP_ALLOW_K13_OPTION_MASK  = H5_SZIP_ALLOW_K13_OPTION_MASK   #1             # <<<<<<<<<<<<<<
 * SZIP_CHIP_OPTION_MASK       = H5_SZIP_CHIP_OPTION_MASK        #2
 * SZIP_EC_OPTION_MASK         = H5_SZIP_EC_OPTION_MASK          #4
 */
  __pyx_t_2 = PyInt_FromLong(H5_SZIP_ALLOW_K13_OPTION_MASK); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_2, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":47
 * 
 * SZIP_ALLOW_K13_OPTION_MASK  = H5_SZIP_ALLOW_K13_OPTION_MASK   #1
 * SZIP_CHIP_OPTION_MASK       = H5_SZIP_CHIP_OPTION_MASK        #2             # <<<<<<<<<<<<<<
 * SZIP_EC_OPTION_MASK         = H5_SZIP_EC_OPTION_MASK          #4
 * SZIP_NN_OPTION_MASK         = H5_SZIP_NN_OPTION_MASK          #32
 */
  __pyx_t_2 = PyInt_FromLong(H5_SZIP_CHIP_OPTION_MASK); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_3, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":48
 * SZIP_ALLOW_K13_OPTION_MASK  = H5_SZIP_ALLOW_K13_OPTION_MASK   #1
 * SZIP_CHIP_OPTION_MASK       = H5_SZIP_CHIP_OPTION_MASK        #2
 * SZIP_EC_OPTION_MASK         = H5_SZIP_EC_OPTION_MASK          #4             # <<<<<<<<<<<<<<
 * SZIP_NN_OPTION_MASK         = H5_SZIP_NN_OPTION_MASK          #32
 * SZIP_MAX_PIXELS_PER_BLOCK   = H5_SZIP_MAX_PIXELS_PER_BLOCK    #32
 */
  __pyx_t_2 = PyInt_FromLong(H5_SZIP_EC_OPTION_MASK); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_SZIP_EC_OPTION_MASK, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":49
 * SZIP_CHIP_OPTION_MASK       = H5_SZIP_CHIP_OPTION_MASK        #2
 * SZIP_EC_OPTION_MASK         = H5_SZIP_EC_OPTION_MASK          #4
 * SZIP_NN_OPTION_MASK         = H5_SZIP_NN_OPTION_MASK          #32             # <<<<<<<<<<<<<<
 * SZIP_MAX_PIXELS_PER_BLOCK   = H5_SZIP_MAX_PIXELS_PER_BLOCK    #32
 * 
 */
  __pyx_t_2 = PyInt_FromLong(H5_SZIP_NN_OPTION_MASK); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_SZIP_NN_OPTION_MASK, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":50
 * SZIP_EC_OPTION_MASK         = H5_SZIP_EC_OPTION_MASK          #4
 * SZIP_NN_OPTION_MASK         = H5_SZIP_NN_OPTION_MASK          #32
 * SZIP_MAX_PIXELS_PER_BLOCK   = H5_SZIP_MAX_PIXELS_PER_BLOCK    #32             # <<<<<<<<<<<<<<
 * 
 * FILTER_CONFIG_ENCODE_ENABLED = H5Z_FILTER_CONFIG_ENCODE_ENABLED
 */
  __pyx_t_2 = PyInt_FromLong(H5_SZIP_MAX_PIXELS_PER_BLOCK); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_4, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":52
 * SZIP_MAX_PIXELS_PER_BLOCK   = H5_SZIP_MAX_PIXELS_PER_BLOCK    #32
 * 
 * FILTER_CONFIG_ENCODE_ENABLED = H5Z_FILTER_CONFIG_ENCODE_ENABLED             # <<<<<<<<<<<<<<
 * FILTER_CONFIG_DECODE_ENABLED = H5Z_FILTER_CONFIG_DECODE_ENABLED
 * 
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_CONFIG_ENCODE_ENABLED); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_5, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":53
 * 
 * FILTER_CONFIG_ENCODE_ENABLED = H5Z_FILTER_CONFIG_ENCODE_ENABLED
 * FILTER_CONFIG_DECODE_ENABLED = H5Z_FILTER_CONFIG_DECODE_ENABLED             # <<<<<<<<<<<<<<
 * 
 * ERROR_EDC   = H5Z_ERROR_EDC
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_FILTER_CONFIG_DECODE_ENABLED); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_6, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":55
 * FILTER_CONFIG_DECODE_ENABLED = H5Z_FILTER_CONFIG_DECODE_ENABLED
 * 
 * ERROR_EDC   = H5Z_ERROR_EDC             # <<<<<<<<<<<<<<
 * DISABLE_EDC = H5Z_DISABLE_EDC
 * ENABLE_EDC  = H5Z_ENABLE_EDC
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_ERROR_EDC); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_ERROR_EDC, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":56
 * 
 * ERROR_EDC   = H5Z_ERROR_EDC
 * DISABLE_EDC = H5Z_DISABLE_EDC             # <<<<<<<<<<<<<<
 * ENABLE_EDC  = H5Z_ENABLE_EDC
 * NO_EDC      = H5Z_NO_EDC
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_DISABLE_EDC); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_DISABLE_EDC, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":57
 * ERROR_EDC   = H5Z_ERROR_EDC
 * DISABLE_EDC = H5Z_DISABLE_EDC
 * ENABLE_EDC  = H5Z_ENABLE_EDC             # <<<<<<<<<<<<<<
 * NO_EDC      = H5Z_NO_EDC
 * 
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_ENABLE_EDC); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_ENABLE_EDC, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pyx":58
 * DISABLE_EDC = H5Z_DISABLE_EDC
 * ENABLE_EDC  = H5Z_ENABLE_EDC
 * NO_EDC      = H5Z_NO_EDC             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_t_2 = PyInt_FromLong(H5Z_NO_EDC); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_2);
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_NO_EDC, __pyx_t_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;

  /* "/media/storage/Documents/Work/Examproject/Devel/branch_gpaw/c/h5py/h5z.pxd":1
 * #+             # <<<<<<<<<<<<<<
 * #
 * # This file is part of h5py, a low-level Python interface to the HDF5 library.
 */
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_1);
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_AddTraceback("h5z");
  Py_DECREF(__pyx_m); __pyx_m = 0;
  __pyx_L0:;
  __Pyx_FinishRefcountContext();
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
}

static const char *__pyx_filenames[] = {
  "h5z.pyx",
  "h5.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE int __Pyx_StrEq(const char *s1, const char *s2) {
     while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
     return *s1 == *s2;
}

static INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned char)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (unsigned char)-1;
            if (unlikely(val < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned char");
                return (unsigned char)-1;
            }
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return (unsigned char)val;
    }
    return (unsigned char)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned short)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (unsigned short)-1;
            if (unlikely(val < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned short");
                return (unsigned short)-1;
            }
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return (unsigned short)val;
    }
    return (unsigned short)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject* x) {
    if (sizeof(unsigned int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned int)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (unsigned int)-1;
            if (unlikely(val < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned int");
                return (unsigned int)-1;
            }
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to unsigned int");
            return (unsigned int)-1;
        }
        return (unsigned int)val;
    }
    return (unsigned int)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE char __Pyx_PyInt_AsChar(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(char)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (char)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to char");
            return (char)-1;
        }
        return (char)val;
    }
    return (char)__Pyx_PyInt_AsLong(x);
}

static INLINE short __Pyx_PyInt_AsShort(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(short)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (short)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to short");
            return (short)-1;
        }
        return (short)val;
    }
    return (short)__Pyx_PyInt_AsLong(x);
}

static INLINE int __Pyx_PyInt_AsInt(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(int)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (int)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to int");
            return (int)-1;
        }
        return (int)val;
    }
    return (int)__Pyx_PyInt_AsLong(x);
}

static INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed char)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (signed char)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to signed char");
            return (signed char)-1;
        }
        return (signed char)val;
    }
    return (signed char)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed short)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (signed short)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to signed short");
            return (signed short)-1;
        }
        return (signed short)val;
    }
    return (signed short)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed int)val)) {
            if (unlikely(val == -1 && PyErr_Occurred()))
                return (signed int)-1;
            PyErr_SetString(PyExc_OverflowError,
                           "value too large to convert to signed int");
            return (signed int)-1;
        }
        return (signed int)val;
    }
    return (signed int)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned long");
            return (unsigned long)-1;
        }
        return (unsigned long)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        if (unlikely(Py_SIZE(x) < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned long");
            return (unsigned long)-1;
        }
        return PyLong_AsUnsignedLong(x);
    } else {
        unsigned long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned long)-1;
        val = __Pyx_PyInt_AsUnsignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned PY_LONG_LONG");
            return (unsigned PY_LONG_LONG)-1;
        }
        return (unsigned PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        if (unlikely(Py_SIZE(x) < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned PY_LONG_LONG");
            return (unsigned PY_LONG_LONG)-1;
        }
        return PyLong_AsUnsignedLongLong(x);
    } else {
        unsigned PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE long __Pyx_PyInt_AsLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (long)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLong(x);
    } else {
        long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (long)-1;
        val = __Pyx_PyInt_AsLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLongLong(x);
    } else {
        PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (signed long)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLong(x);
    } else {
        signed long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed long)-1;
        val = __Pyx_PyInt_AsSignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject* x) {
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_CheckExact(x) || PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        return (signed PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_CheckExact(x) || PyLong_Check(x))) {
        return PyLong_AsLongLong(x);
    } else {
        signed PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsSignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(class_name);
    #else
    py_name = PyUnicode_FromString(class_name);
    #endif
    if (!py_name)
        goto bad;
    result = PyObject_GetAttr(py_module, py_name);
    Py_DECREF(py_name);
    py_name = 0;
    Py_DECREF(py_module);
    py_module = 0;
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_module);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(const char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(name);
    #else
    py_name = PyUnicode_FromString(name);
    #endif
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
#if PY_VERSION_HEX < 0x02050000
    char *api = (char *)"__pyx_capi__";
#else
    const char *api = "__pyx_capi__";
#endif
    PyObject *d = 0;
    PyObject *cobj = 0;
    const char *desc;
    const char *s1, *s2;
    union {
        void (*fp)(void);
        void *p;
    } tmp;

    d = PyObject_GetAttrString(module, api);
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%s does not export expected C function %s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    desc = (const char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    s1 = desc; s2 = sig;
    while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
    if (*s1 != *s2) {
        PyErr_Format(PyExc_TypeError,
            "C function %s.%s has wrong signature (expected %s, got %s)",
             PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    tmp.p = PyCObject_AsVoidPtr(cobj);
    *f = tmp.fp;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if ((x == Py_False) | (x == Py_None)) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x) {
  PyNumberMethods *m;
  const char *name = NULL;
  PyObject *res = NULL;
#if PY_VERSION_HEX < 0x03000000
  if (PyInt_Check(x) || PyLong_Check(x))
#else
  if (PyLong_Check(x))
#endif
    return Py_INCREF(x), x;
  m = Py_TYPE(x)->tp_as_number;
#if PY_VERSION_HEX < 0x03000000
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Int(x);
  }
  else if (m && m->nb_long) {
    name = "long";
    res = PyNumber_Long(x);
  }
#else
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Long(x);
  }
#endif
  if (res) {
#if PY_VERSION_HEX < 0x03000000
    if (!PyInt_Check(res) && !PyLong_Check(res)) {
#else
    if (!PyLong_Check(res)) {
#endif
      PyErr_Format(PyExc_TypeError,
                   "__%s__ returned non-%s (type %.200s)",
                   name, name, Py_TYPE(res)->tp_name);
      Py_DECREF(res);
      return NULL;
    }
  }
  else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_TypeError,
                    "an integer is required");
  }
  return res;
}

static INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t ival) {
#if PY_VERSION_HEX < 0x02050000
   if (ival <= LONG_MAX)
       return PyInt_FromLong((long)ival);
   else {
       unsigned char *bytes = (unsigned char *) &ival;
       int one = 1; int little = (int)*(unsigned char*)&one;
       return _PyLong_FromByteArray(bytes, sizeof(size_t), little, 0);
   }
#else
   return PyInt_FromSize_t(ival);
#endif
}

static INLINE size_t __Pyx_PyInt_AsSize_t(PyObject* x) {
   unsigned PY_LONG_LONG val = __Pyx_PyInt_AsUnsignedLongLong(x);
   if (unlikely(val == (unsigned PY_LONG_LONG)-1 && PyErr_Occurred())) {
       return (size_t)-1;
   } else if (unlikely(val != (unsigned PY_LONG_LONG)(size_t)val)) {
       PyErr_SetString(PyExc_OverflowError,
                       "value too large to convert to size_t");
       return (size_t)-1;
   }
   return (size_t)val;
}


